### ISSUE TITLE
Another version of the TEAC FD-235HF to share with different component references

### ISSUE THREAD

**Issue by ljmarent** [schlae/amiga-hddlw#3]
TEAC FD-235HF C829

![Screen Shot 2024-05-17 at 3 56 25 PM](https://github.com/schlae/amiga-hddlw/assets/33465449/eaf5abde-2b51-4fa1-a39a-25e6e69ccdc3)

Multi-meter identifies R12 and S6 are the target parts on this version of the PCB

**Comment by schlae** [comment]
Thank you, can you provide a top-down photo of the PCB so I can include it?

**Comment by ljmarent** [comment]
![IMG_2623](https://github.com/schlae/amiga-hddlw/assets/33465449/7b560ad5-1331-4738-b406-633e0a30c8e9)

**Comment by schlae** [comment]
Thanks, it has been added.
